import React from "react";
import {
  Music,
  Trophy,
  Book,
  Plane,
  Utensils,
  Gamepad2,
  Film,
  Camera,
  Palette,
  Dumbbell,
  Dog,
  Monitor,
  Star,
  Headphones,
  Mic,
  Guitar,
  Piano,
  Tent,
  Mountain,
  Map,
  Compass,
  Bike,
  Waves,
  Trees,
  CloudSun,
  Coffee,
  Beer,
  Pizza,
  ShoppingBag,
  Shirt,
  Watch,
  Heart,
  Briefcase,
  Code,
  Smartphone,
  Cpu,
  Globe,
  Languages,
  PenTool,
  Hammer,
  Wrench,
  Car,
  Bus,
  Train,
  Ship,
  Anchor,
  Rocket,
  Atom,
  FlaskConical,
  Stethoscope,
  GraduationCap,
  School,
  Building,
  Home,
  Users,
  Smile,
  Leaf,
  Flower2,
  Fish,
  Bird,
  Cat,
  Footprints,
  Baby,
  Dice5,
  Puzzle,
  Spade,
  Club,
  Ticket,
  Clapperboard,
  Video,
  Image,
  Brush,
  Scissors,
  Droplets,
  Zap,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Umbrella,
  Wind,
  Tornado,
  Palmtree,
  TentTree,
  Thermometer,
  Activity,
  HeartPulse,
  Brain,
  Lightbulb,
  Glasses,
  Crown,
  Gem,
  Gift,
  Ghost,
  Skull,
  Locate,
  Navigation,
  Flag,
  Target,
  Medal,
  Award,
  Swords,
  Shield,
  ZapOff,
} from "lucide-react";

const iconMap = {
  // Arts & Music
  music_note: Music,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  guitar: Guitar,
  piano: Piano,
  palette: Palette,
  brush: Brush,
  film: Film,
  movie: Film,
  video: Video,
  camera: Camera,
  photo_camera: Camera,
  image: Image,
  clapperboard: Clapperboard,
  book: Book,
  menu_book: Book,
  pen_tool: PenTool,

  // Sports & Fitness
  trophy: Trophy,
  sports_soccer: Trophy, // Fallback for soccer
  medal: Medal,
  award: Award,
  dumbbell: Dumbbell,
  fitness_center: Dumbbell,
  activity: Activity,
  heart_pulse: HeartPulse,
  bike: Bike,
  directions_bike: Bike,
  swords: Swords,
  shield: Shield,
  target: Target,
  flag: Flag,

  // Travel & Adventure
  plane: Plane,
  flight: Plane,
  map: Map,
  compass: Compass,
  globe: Globe,
  mountain: Mountain,
  hiking: Mountain,
  tent: Tent,
  camping: Tent,
  tent_tree: TentTree,
  palmtree: Palmtree,
  anchor: Anchor,
  ship: Ship,
  car: Car,
  bus: Bus,
  train: Train,
  rocket: Rocket,
  navigation: Navigation,
  locate: Locate,

  // Food & Drink
  restaurant: Utensils,
  utensils: Utensils,
  coffee: Coffee,
  beer: Beer,
  pizza: Pizza,

  // Gaming & Tech
  gamepad: Gamepad2,
  sports_esports: Gamepad2,
  monitor: Monitor,
  computer: Monitor,
  smartphone: Smartphone,
  cpu: Cpu,
  code: Code,
  zap: Zap,
  zap_off: ZapOff,

  // Nature & Animals
  dog: Dog,
  pets: Dog,
  cat: Cat,
  bird: Bird,
  fish: Fish,
  footprints: Footprints,
  leaf: Leaf,
  flower: Flower2,
  trees: Trees,
  flame: Flame,
  droplets: Droplets,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  cloud_sun: CloudSun,
  wind: Wind,
  tornado: Tornado,
  umbrella: Umbrella,

  // Job & Education
  briefcase: Briefcase,
  work: Briefcase,
  graduation_cap: GraduationCap,
  school: School,
  school_outline: School,
  building: Building,
  home: Home,
  wrench: Wrench,
  hammer: Hammer,
  stethoscope: Stethoscope,
  flask: FlaskConical,
  atom: Atom,

  // Fashion & Shopping
  shopping_bag: ShoppingBag,
  shirt: Shirt,
  watch: Watch,
  glasses: Glasses,
  gem: Gem,
  crown: Crown,
  gift: Gift,

  // Misc
  star: Star,
  heart: Heart,
  users: Users,
  smile: Smile,
  baby: Baby,
  dice: Dice5,
  puzzle: Puzzle,
  spade: Spade,
  club: Club,
  ticket: Ticket,
  scissors: Scissors,
  thermometer: Thermometer,
  brain: Brain,
  lightbulb: Lightbulb,
  ghost: Ghost,
  skull: Skull,
};

export const getIconComponent = (iconName, props = {}) => {
  // Normalize icon name: lowercase and trim
  const normalizedKey = iconName ? String(iconName).toLowerCase().trim() : "";

  // Try exact match, direct mapping, or fallback
  const Icon = iconMap[normalizedKey] || iconMap[iconName] || Star;

  return <Icon {...props} />;
};

export default iconMap;
